//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Entrepot
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GestionEntrepotEntities2 : DbContext
    {
        public GestionEntrepotEntities2()
            : base("name=GestionEntrepotEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ListColis> ListColis { get; set; }
        public virtual DbSet<View_Colis> View_Colis { get; set; }
        public virtual DbSet<View_Effet> View_Effet { get; set; }
        public virtual DbSet<View_FicheMagasin> View_FicheMagasin { get; set; }
        public virtual DbSet<View_Mouvement> View_Mouvement { get; set; }
        public virtual DbSet<View_Retrait> View_Retrait { get; set; }
        public virtual DbSet<View_Stock_Restant> View_Stock_Restant { get; set; }
    
        public virtual ObjectResult<statistiqueproc_Result> statistiqueproc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<statistiqueproc_Result>("statistiqueproc");
        }
    }
}
