//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Entrepot
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListColis
    {
        public int id_Colis { get; set; }
        public string Designation { get; set; }
        public string Plaque { get; set; }
        public string Importateur { get; set; }
        public string Manifeste { get; set; }
        public string Declarant { get; set; }
        public string Plomb { get; set; }
        public int Quantite { get; set; }
        public string Nature { get; set; }
        public System.DateTime Date { get; set; }
    }
}
