//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Entrepot
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Effet
    {
        public int ID { get; set; }
        public string Retrait { get; set; }
        public string Colis { get; set; }
        public string Plaque { get; set; }
        public string Nature { get; set; }
        public int Quantite { get; set; }
        public string Declarant { get; set; }
        public string Plaque_Sortie { get; set; }
        public string Nom_Chauffeur { get; set; }
        public string Num_Chauffeur { get; set; }
        public string Date { get; set; }
        public byte[] CodeQR { get; set; }
    }
}
