//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Entrepot
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Mouvement
    {
        public string Type { get; set; }
        public string Date { get; set; }
        public string Colis { get; set; }
        public string Plaque { get; set; }
        public string Declarant { get; set; }
        public string Importateur { get; set; }
    }
}
